version: '3'
services:
  gpt_server:
    # 构建
    build:
      context: .
      dockerfile: Dockerfile.copy
    image: gpt_server:runtime_v0.0.2
    container_name: gpt_server
    network_mode: host
    ports:
      - "8082:8082"
    volumes:
      - "/home/dev/model/:/home/dev/model/"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0','1' ]
              # count: 2  # 两种方式
              capabilities: [ gpu ]
    command: python gpt_server/serving/main.py
