[tool.poetry]
name = "gpt-server"
version = "0.0.1"
description = ""
authors = ["liuyu <506610466@qq.com>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sentence-transformers = "^2.2.2"
fschat = "0.2.36"
loguru = "^0.7.2"
distribute = "^0.7.3"
transformers-stream-generator = "^0.0.4"
openai = "0.28.0"
vllm = "^0.3.3"
ray = "^2.9.0"
accelerate = "^0.27.2"

[[tool.poetry.source]]
name = "ustc"
url = "https://mirrors.ustc.edu.cn/pypi/web/simple"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
