serve_args:
  host: 0.0.0.0
  port: 8082

models:
  chatglm3-6b-2:  #自定义的模型名称
    alias: gpt4,gpt3 # 别名     例如  gpt4,gpt3
    enable: true  # false true
    model_name_or_path: /home/dev/model/chatglm3-6b/
    model_type: chatglm3  # qwen  chatglm3
    work_mode: hf  # accelerate  deepspeed hf

    workers:
    - gpus:
      # - 1
      - 2
      # - 3
    # - gpus:
    #   - 0
  yi:  #自定义的模型名称
    alias: gpt4,gpt3 # 别名     例如  gpt4,gpt3
    enable: false  # false true
    model_name_or_path: /home/dev/model/01ai/Yi-34B-Chat/
    model_type: yi  # qwen  chatglm3
    work_mode: deepspeed  # accelerate  deepspeed hf

    workers:
    - gpus:
      - 2
      - 1
    
  # Embedding 模型
  piccolo-base-zh:
    alias: null # 别名   
    enable: false  # false true
    model_name_or_path: /home/dev/model/assets/embeddings/sensenova/piccolo-base-zh/
    model_type: embedding
    work_mode: deepspeed

    workers:
    - gpus:
      - 0








